# 09. 구문 오류 및 예외 처리

> 파이썬의 에러는 해석 단계에서 발생하는 **구문 오류**와 실행 단계에서 발생하는 **예외**로 구분된다. 오류 메세지를 보고 어떤 단계에서 에러가 발생했는지 확인하는 것이 중요하고, 각각 가지는 의미가 다르다.

[🏠Home](https://github.com/batboy118/Study_Note)

[◀Previous page ](./README.md)

---

<!-- TOC -->

- [1. 구문 오류와 예외](#1-구문-오류와-예외)
- [2. 예외 처리 방법](#2-예외-처리-방법)
	- [2.1. try ~ except 문](#21-try--except-문)
	- [2.2. try ~ except ~ else 문](#22-try--except--else-문)
	- [2.3. try ~ except ~ else ~ finally 문](#23-try--except--else--finally-문)
- [3. 예외 객체](#3-예외-객체)
	- [3.1. 예외 객체란](#31-예외-객체란)
	- [3.2. 예외 객체에 따른 처리의 분기](#32-예외-객체에-따른-처리의-분기)
- [4. 강제 예외 발생](#4-강제-예외-발생)
- [5. 예외 만들기](#5-예외-만들기)

<!-- /TOC -->

## 1. 구문 오류와 예외

- 구문 오류(`SyntaxError`)

  문법적 오류

  ![image](https://user-images.githubusercontent.com/53181778/77884897-7ccfc800-7255-11ea-96d0-f9f3f0988146.png)

- 예외

  문법적인 문제는 없지만, 실행 중에 예기치 않게 발생함

  ex) 인덱스 범위 초과

  ![image](https://user-images.githubusercontent.com/53181778/77884969-a852b280-7255-11ea-9016-e8b58745603f.png)

## 2. 예외 처리 방법

- `try ~ except`문
  - 예외가 발생했을 때 처리
- `try ~ except ~ else`문\
  - 예외가 발생 했을 때와 예외가 발생하지 않았을 때 처리

- `try ~ except ~else ~ finally`문
  - 예외가 발생 했을 때와 예외가 발생하지 않았을 때, 예외 발생과 상관 없이 실행

### 2.1. try ~ except 문

```python
try :
    명령문
    명령문
except :
	예외가 발생했을 때
```

- try 내부에서 어떠한 에러(예외)가 발생하게 되면 except를 실행함

  ```python
  width = input("폭을 입력하세요: ")
  height = input("높이를 입력하세요: ")
  area = 0

  try:
      area = int(width) * int(height)
      print(area)
  except:
      print("숫자가 아닌 값이 입력되었습니다.")
  ```

### 2.2. try ~ except ~ else 문

```python
try :
    명령문
    명령문
except :
	예외가 발생했을 때
else :
	예외가 발생하지 않았을 때
```

- try 내부에서 어떠한 에러(예외)가 발생하게 되면 except를 실행하고 발생하지 않으면, else를 실행함

  ```python
  width = input("폭을 입력하세요: ")
  height = input("높이를 입력하세요: ")
  area = 0

  try:
      area = int(width) * int(height)
  except:
      print("숫자가 아닌 값이 입력되었습니다.")
  else :
  	print(area)
  ```

### 2.3. try ~ except ~ else ~ finally 문

```python
try :
    명령문
    명령문
except :
	예외가 발생했을 때
else :
	예외가 발생하지 않았을 때
finally :
    예외처리와 상관없이 출력
```

- finally 는 예외의 발생과 상관없이 except나 else가 실행된 후 실행된다.

  ```python
  width = input("폭을 입력하세요: ")
  height = input("높이를 입력하세요: ")
  area = 0

  try:
      area = int(width) * int(height)
  except:
      print("숫자가 아닌 값이 입력되었습니다.")
  else :
  	print(area)
  finally :
      print("프로그램 종료")
  ```

## 3. 예외 객체

### 3.1. 예외 객체란

코드를 실행하는 도중 오류가 발생하면 만들어지는 객체로, 오류의 정보를 담고 있음

```python
try :
	명령문
except Exception as 객체명:
    객체 활용한 예외 처리 문
```

- 예시

  예외의 에러 메세지를 객체로 받아 출력하기

  ```python
  width = input("폭을 입력하세요: ")
height = input("높이를 입력하세요: ")
  area = 0

  try:
      area = int(width) * int(height)
  except Exception as ex:
  	print("{0} : {1}".format(type(ex),ex))
  else :
    print("{0} x {1} = {2}".format(width, height, area))
  ```

  - 결과

    > 폭을 입력하세요 : 5
    >
    > 높이를 입력하세요 : ㄱ
    >
    > <calss 'ValueError'> : invalid literal for int() with base 10 : 'ㄱ'

### 3.2. 예외 객체에 따른 처리의 분기

- except를 여러개 사용하여 에러의 종류에 따라 예외 처리를 따로 해줄 수 있다.

- 예시

  >참고
  >
  >ValueError : 숫자 문자 형식이 아닌 문자를 숫자로 변환 할 때 발생하는 객체
  >
  >ZeroDivisionError : 0으로 나눌때 발생하는 오류 객체

  ```python
  x, y, result = 0, 0, 0

  try :
      x = int(input("피제수를 입력하세요: "))
      y = int(input("제수를 입력하세요: "))
      result = x/ y

  except ValueError:
      print("입력 값은 반드시 숫자를 사용해야 합니다.")
  except ZeroDivisionError:
      print("제수로 0을 사용할 수 없습니다.")
  ```

  - 제수에 0을 넣으면 `ZeroDivisionError`이 발생
  - 올바르지 않은 값이 들어오면 `ValueError`이 발생

## 4. 강제 예외 발생

런타임에 의해서가 아닌, 특정 조건에서 예외 객체를 만들어 예외를 일으 킬 수 있다.

이때, raise 문을 사용하여 특정 예외와 메세지를 던질 수 있다.

```python
def clac_area(w, h):
	if w.isdigit() and h isdigit():
		return int(w) * int(h)
    else:
        raise ValueError("숫자가 아닌 값이 입력되었습니다.")

width = input("폭을 입력하세요: ")
height = input("높이를 입력하세요: ")
area = 0

try:
    area = clac_area(width, height)
except Value as ve:
	print("{0} : {1}".format(type(ve),ve))
except Exception as ex:
	print("{0} : {1}".format(type(ex),ex))
else :
    print("{0} x {1} = {2}".format(width, height, area))
```

- 결과

  >폭을 입력하세요 : 5
  >
  >높이를 입력하세요 : ㄱ
  >
  ><calss 'ValueError'> : 숫자가 아닌 값이 입력되었습니다.

- `raise`를 이용하여 `숫자가 아닌 값이 입력되었습니다.`라는 메세지와 함께 `ValueError` 예외를 던짐

> 참고)
>
> **assert로 예외 발생시키기**
>
> 예외를 발생시키는 방법 중에는 assert를 사용하는 방법도 있다. assert는 지정된 조건식이 거짓일 때 AssertionError 예외를 발생시키며 조건식이 참이면 그냥 넘긴다. 보통 assert는 나와서는 안 되는 조건을 검사할 때 사용한다.
>
> assert는 **디버깅 모드**에서만 실행됩니다. 특히 파이썬은 기본적으로 디버깅 모드이며(`__debug__`의 값이 True) assert가 실행되지 않게 하려면 python에 -O 옵션을 붙여서 실행합니다(영문 대문자 O).
>
> `python -O 스크립트파일.py`
>
> 예시) 3의 배수가 아닐 때 예외
>
> ```python
> x = int(input('3의 배수를 입력하세요: '))
> assert x % 3 == 0, '3의 배수가 아닙니다.'    # 3의 배수가 아니면 예외 발생, 3의 배수이면 그냥 넘어감
> print(x)
> ```
>
> - 결과
>
>   > 3의 배수를 입력하세요: 5 (입력)
>   > Traceback (most recent call last):
>   >
>   > File "C:\project\assertion.py", line 2, in <module>
>   >     assert x % 3 == 0, '3의 배수가 아닙니다.'
>   > AssertionError: 3의 배수가 아닙니다.

## 5. 예외 만들기

- Exception 클래스를 상속 받아 새로운 클래스를 만들면 된다. 그리고, `__init__` 메서드에서 기반 클래스의 `__init__` 메서드를 호출하면서 에러메세지를 넣어주면 된다.

  ```python
  class 예외이름(Exception):
      def __init__(self):
          super().__init__('에러메시지')
  ```

- 예시

  3의 배수가 아닐 때 발생시킬 예외 만들기

  ```python
  class NotThreeMultipleError(Exception):    # Exception을 상속받아서 새로운 예외를 만듦
      def __init__(self):
          super().__init__('3의 배수가 아닙니다.')

  def three_multiple():
      try:
          x = int(input('3의 배수를 입력하세요: '))
          if x % 3 != 0:                     # x가 3의 배수가 아니면
              raise NotThreeMultipleError    # NotThreeMultipleError 예외를 발생시킴
          print(x)
      except Exception as e:
          print('예외가 발생했습니다.', e)

  three_multiple()
  ```

  - 결과

    > 3의 배수를 입력하세요: 5 (입력)
    > 예외가 발생했습니다. 3의 배수가 아닙니다.
