# 08. Callback

> 자바스크립트의 Callback에 대해 학습

[🏠Home](https://github.com/batboy118/Study_Note)

[◀Previous page ](./README.md)

---

<!-- TOC -->

- [1. callback](#1-callback)
- [2. callback Hell](#2-callback-hell)
- [3. Promise](#3-promise)
- [4. Promise Chaining](#4-promise-chaining)
- [5. callback Hell Promise로 개선하기](#5-callback-hell-promise로-개선하기)
- [6. async & await](#6-async--await)
	- [6.1. async](#61-async)
	- [6.2. await](#62-await)
- [7. callback Hell async & await으로 개선하기](#7-callback-hell-async--await으로-개선하기)

<!-- /TOC -->

## 1. callback

callback은 자바스크립트에서 비동기의 시작이다.

보통 자바스크립트는 동기언어이지만, callback을 쓰면 비동기적으로 동작하게 된다.

예를들어 아래 setTimeout으로 전달된 함수가 callback 함수이다.

```js
setTimeout(function () {
	console.log('2');
}, 1000);
```

callback함수도 두 가지로 나눌 수 있다.

- 동기 콜백

  ```js
  function printNow(print){
      print();
  }
  printNow(()=>console.log("Hello"));
  ```

- 비동기 콜백

  ```js
  function printNow(print){
      setTimeout(()=>console.log("Hello"), 1000);
  }
  printNow(()=>console.log("Hello"));
  ```

## 2. callback Hell

콜백 지옥의 예시를 살펴보자.

```js
class UserStorage {
    loginUser(id, password, onSuccess, onError){
        setTimeout(() => {
            if(
                (id === 'jason' && password === 'bear') ||
                (id === 'peter' && password === 'bat')
            ) {
                onSuccess(id);
            } else {
                onError(new Error('not found'));
            }
        }, 2000);
    }

    getRoles(user, onSuccess, onError){
        setTimeout(() => {
            if(user === 'jason') {
                onSuccess({name: 'jason', role: 'admin'});
            } else {
                onError(new Error('no access'));
            }
        },1000);
    }
}

const userStorage = new UserStorage();
const id = prompt ('endter your id');
const password = prompt ('endter your password');
userStorage.loginUser(
    id,
    password,
    (user) => {
        userStorage.getRoles(
            user,
            (uerWithRole) => {
                alert(`Hello ${uerWithRole.name}, you are ${uerWithRole.role}!`)
            },
            (error) => {console.log("Error")}
        )},
    (error) => {console.log("Error")}
)
```

- 위 코드는 id와 password를 입력하여 로그인하고, 역할을 받고, 유저를 확인하여 출력한다.

- 가독성이 좋지 않다.
- 디버깅하기 어렵다.
- 유지보수도 어렵다.

## 3. Promise

promise는 비동기를 간편하게 처리할 수 있도록 자바스크립트에서 제공해주는 Object이다.

인스턴스에 비동기적으로 상태가 갱신되고, 값이 저장된다.

Promise는 정해진 비동기 작업이 정상적으로 처리가 되었다면, 성고의 메세지와 함께 결과값을 전달해주고, 실패하면 에러를 던져준다.

비동기적인 것을 실행할 때 콜백함수 대신에 쓰인다.

promise를 사용하기 위해서는 상태(state), 제공자(producer), 소비자(consumer)에 대한 이해가 필요하다.

- state

  - pending : Promise가 만들어져서 지정된 작업이 실행되는 상태
  - fulfilled : 정해진 작업을 끝낸 상태
  - rejected : 문제가 발생한 상태

- producer : 프로미스를 만드는 것

  ```js
  const promise = new Promise((resolve, reject) => {
      console.log('doing Something');
      setTimeout(() => {
          resolve('jason');
      }, 2000);
  })
  //doing Something
  ```

  - promise는 resolve와 reject를 가지는 excutor(callback) 함수를 받는다.
  - 보통 비동기는 연산량이 많은 작업에 사용을 하게 된다.
  - **promise 인스턴스를 만드는 것만으로도, 콜백함수가 실행이 된다!**
    - doing Something이 출력된다.
    - 이것을 항상 염두해야 한다.(주의)
  - 위 예시에서는 2초 후에 resolve라는 함수에 jason 스트링을 인자로 주어 실행한다.

  ```js
  const promise = new Promise((resolve, reject) => {
      setTimeout(() => {
          reject(new Error('no network'));
      }, 2000);
  })
  ```

  - reject함수를 실행시킬 때는 보통 Error 객체를 생성해서 전달해주는데, 위 코드의 경우 2초 후에 에러를 발생시켜 프로그램을 죽인다.

- consumer : 프로미스를 사용하는 것

  - then, catch, finally 를 이용해서 값을 받아 올 수 있다.

  ```js
  const promise = new Promise((resolve, reject) => {
      setTimeout(() => {
          resolve('jason');
      }, 2000);
  })

  promise.then((value) => {
      console.log(value);
  })
  //jason
  ```

  - then은 프로미스에서 resolve로 전달한 값을 파라미터로 받아서 실행시켜준다.

  ```js
  const promise = new Promise((resolve, reject) => {
      setTimeout(() => {
          reject(new Error('no network'));
      }, 2000);
  })

  promise
      .then((value) => {
      console.log(value);
  })
      .catch(error => {
      console.log(error);
  });
  //error
  ```

  - 에러가 발생했을 때 프로그램을 멈추지 않고 특별한 처리를 하고 싶다면 `catch`를 사용하면 된다.
  - 위 코드는 콘솔에 error 객체를 출력할뿐 프로그램을 죽이지는 않는다.
  - 위 코드의 체이닝이 가능한 이유는, `then`은 **promise 객체**를 리턴하기 때문이다.

  최근에는 **finally**라는 메서드가 추가되었는데,  이 코드는 resolve나 reject에 관계 없이 무조건 실행되는 함수이다.

  ```js
  const promise = new Promise((resolve, reject) => {
      setTimeout(() => {
          reject(new Error('no network'));
      }, 2000);
  })

  promise
      .then((value) => {
      console.log(value);
  })
      .catch(error => {
      console.log(error);
  })
      .finally(()=>{
      console.log("Always")
  });
  //error
  ```

> resolve함수나 reject 함수가 실행될 떄 까지 `pending`상태이다.

## 4. Promise Chaining

```js
const fetchNumber = new Promise((resolve, reject) => {
    setTimeout(() => resolve(3), 2000);
})

fetchNumber
    .then(num => num * 2)   // 6
    .then(num => num * 3)   // 18
    .then(num => {
    return new Promise((resolve, reject) => {
        setTimeout(() => resolve(num - 1), 1000);    //17
    });
})
    .then(num => console.log(num));
//17
```

- then은 값이 콜백함수의 리턴값으로 갱신된 새로운 Promise 객체를 반환한다. 내부적으로 콜백함수의 리턴값이 프로미스 객체이면 그 프로미스 객체가 생성되며 then의 리턴갑 자체가 된다.

새로운 예시를 살펴보자.

```js
const getHen = () => new Promise((resolve, reject) => {
    setTimeout(() => resolve("닭"), 1000)
});

const getEgg = hen => new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${hen} => "달걀"`), 1000)
});

const cook = egg => new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${egg} => "요리"`), 1000)
});

getHen()
    .then(hen => getEgg(hen))
    .then(egg => cook(egg))
    .then(meal => console.log(meal))
//닭 => "달걀" => "요리"
```

- 위 코드를 조금더 간단히 할 수 있다.
- 매개변수와 콜백함수의 인자가 같다면 생략할 수 있다.

```js
getHen()
    .then(getEgg)
    .then(cook)
    .then(console.log)
```

만약 중간에 에러가 발생했다고 가정하고, 에러가 발생했을 경우 대처를 해주는 방법을 알아보자.

```js
const getHen = () => new Promise((resolve, reject) => {
    setTimeout(() => resolve("닭"), 1000)
});

const getEgg = hen => new Promise((resolve, reject) => {
    setTimeout(() => reject(new Error(`Error: ${hen} => "달걀"`)), 1000)
});

const cook = egg => new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${egg} => 요리`), 1000)
});

getHen()
    .then(getEgg)
    .then(cook)
    .then(console.log)
	.catch(console.log)
//Error: Error: 닭 => "달걀"
```

- 위와 같이 catch에서 에러를 잡는다. 하지만 에러를 발생시키지 않고, 달걀을 다른 것으로 대체하여 문제 없이 동작시킬 수 있다.

```js
getHen()
    .then(getEgg)
    .catch(error => "빵")
    .then(cook)
    .then(console.log)
//빵 => "요리"
```

- 중간에 에러가 발생 했더라도, 달걀 대신 빵으로 대체된 프로미스가 전달되는 것이다.

## 5. callback Hell Promise로 개선하기

```js
class UserStorage {
    loginUser(id, password, onSuccess, onError){
        setTimeout(() => {
            if(
                (id === 'jason' && password === 'bear') ||
                (id === 'peter' && password === 'bat')
            ) {
                onSuccess(id);
            } else {
                onError(new Error('not found'));
            }
        }, 2000);
    }

    getRoles(user, onSuccess, onError){
        setTimeout(() => {
            if(user === 'jason') {
                onSuccess({name: 'jason', role: 'admin'});
            } else {
                onError(new Error('no access'));
            }
        },1000);
    }
}

const userStorage = new UserStorage();
const id = prompt ('endter your id');
const password = prompt ('endter your password');
userStorage.loginUser(
    id,
    password,
    (user) => {
        userStorage.getRoles(
            user,
            (uerWithRole) => {
                alert(`Hello ${uerWithRole.name}, you are ${uerWithRole.role}!`)
            },
            (error) => {console.log("Error")}
        )},
    (error) => {console.log("Error")}
)
```

위 코드를 promise를 이용해 바꾸어 보자.

```js
class UserStorage {
    loginUser(id, password){
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if(
                    (id === 'jason' && password === 'bear') ||
                    (id === 'peter' && password === 'bat')
                ) {
                    resolve(id);
                } else {
                    reject(new Error('not found'));
                }
            }, 2000);
        });
    }

    getRoles(user){
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if(user === 'jason') {
                    resolve({name: 'jason', role: 'admin'});
                } else {
                    reject(new Error('no access'));
                }
            },1000);
        })
    }
}

const userStorage = new UserStorage();
const id = prompt ('endter your id');
const password = prompt ('endter your password');
userStorage.loginUser(id, password)
    .then(userStorage.getRoles)
    .then(user => alert(`Hello ${user.name}, you are ${user.role}!`));
	.catch(console.log)
```

- 훨씬 간단해 졌다.

## 6. async & await

async & await 은 promise를 조금 더 간결하고, 간편하고 동기적으로 실행되는 것 처럼 보이게 만들어 준다.

여러개의 promise 체이닝을 사용하는 것보다 조금 더 좋은 방법이 되기도 한다.

기존에 존재하는 promise위에 만들어 진 것이다.

### 6.1. async

```js
function fetchUser() {
    return new Promise((resolve, reject) => {
        네트워크 요청 등 (오래걸리는 작업)
        resolve ('jason');
    });
}

const user = fetchUser();
user.then(console.log);
```

위 코드를 `async`를 이용해 조금더 쉽게 바꿀 수 있다.

함수 앞에 async 를 붙여주고 값을 리턴만 해주면 된다.

```js
async function fetchUser() {
    //네트워크 요청 등 (오래걸리는 작업)
    return ('jason');
}

const user = fetchUser();
user.then(console.log);
```

### 6.2. await

await은 async가 붙은 함수에서만 사용이 가능하다.

프로미스객체 또는 프로미스 객체를 반환하는 함수 앞에 사용할 수 있다.

```js
function delay(ms) {
    return new Promis(resolve => setTimeout(resolve, ms));
}

async function getApple() {
    await delay(2000);
    return ('사과');
}

async function getBanana() {
    await delay(2000);
    return ('바나나');
}

//위 코드를 Promise로 바꾸면 아래와 같다.
async function getBanana() {
    return delay(2000)
        .then(() => "바나나")
}
```

- 프로미스를 사용한 체이닝보다 await을 쓰는것이 코드가 더 동기적으로 읽힌다.

```js
function delay(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function getApple() {
    await delay(2000);
    return ('사과');
}

async function getBanana() {
    await delay(2000);
    return ('바나나');
}

function pickFruits() {
    return getApple().then(apple => {
        return getBanana().then(banana => `${apple} + ${banana}`)
    });
}

pickFruits().then(console.log);
//사과 + 바나나
```

- 위 코드를 보면 프로미스도 콜백지옥과 유사한 모습을 보인다.
- pickFruits함수를 바꾸어보자.

```js
async function pickFruits() {
    console.log("getting Apple")
    const apple = await getApple();
    console.log("getting Banana")
    const banana = await getBanana();
    return  `${apple} + ${banana}`
}

pickFruits().then(console.log);
//getting Apple
// 2초
//getting Banana
// 2초
//사과 + 바나나
```

- 위 코드는 문제가 있다.
- Apple과 Banana를 수집하는 것을 병렬로 처리하고 싶은데, 순서에 따라 동기적으로 처리된다.
- 즉 4초가 걸린다.
- 프로미스를 활용하여 문제를 해결할 수 있다.

```js
async function pickFruits() {
    const applePromise = getApple();
    const bananaPromise = getBanana();
    const apple = await applePromise;
    const banana = await bananaPromise;
    return  `${apple} + ${banana}`
}

pickFruits().then(console.log);
```

- 위 코드는 2초만에 만들어진다.
- 하지만, 코드가 좀 지저분해진다. 이경우는 promise에서 제공하는 API를 사용하면 된다.

```js
function pickAllFruits() {
    return Promise.all([getApple(), getBanana()])
    .then(fruits => fruits.join(' + '));
}

pickAllFruits().then(console.log);
//사과 + 바나나
```

- Promise 객체의 static 메서드인 `all` 메서드는, 프로미스들을 배열 형태로받아서, 프로미스를 생성해주는데 그때 각각의 프로미스 값은 배열형태로 저장이 된다.

아래 `race` 메서드는 배열에 있는 프로미스들 중 **가장 먼저 결과를 받는 프로미스 만** 리턴한다.

```js
function pickOnlyOneFruits() {
    return Promise.race([getApple(), getBanana()])
    .then(fruits => fruits);
}

pickOnlyOneFruits().then(console.log);
//사과
```

>  에러 처리는 아래같이 하면 된다.

```js
async function pickFruits() {
    try{
        const apple = await getApple();
        const banana = await getBanana();
    } catch() {
        //에러 처리
    }
    return  `${apple} + ${banana}`
}
```

## 7. callback Hell async & await으로 개선하기

```js
class UserStorage {
    async loginUser(id, password){
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if(
                    (id === 'jason' && password === 'bear') ||
                    (id === 'peter' && password === 'bat')
                ) {
                    resolve(id);
                } else {
                    reject(new Error('not found'));
                }
            }, 2000);
        });
    }

    async getRoles(user){
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if(user === 'jason') {
                    resolve({name: 'jason', role: 'admin'});
                } else {
                    reject(new Error('no access'));
                }
            },1000);
        })
    }
}

const userStorage = new UserStorage();
const id = prompt ('endter your id');
const password = prompt ('endter your password');

async function checkUser() {
  const login = await userStorage.loginUser(id, password);
  const role = await userStorage.getRoles(id);
  return `hello! ${role.name}, you have a ${role.role} role`;
}

checkUser()
    .then(alert)
    .catch(console.log);
```

